arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
#output-localization-file: lib/l10n/localizations/app_localizations.dart
nullable-getter: false
untranslated-messages-file: untranslated.json
#untranslated-messages-file: lib/l10n/localizations/untranslated.json