import '../app/features/products/domain/categories_apis.dart';
import '../app/features/products/presentation/products_controller.dart';

class FakeData {
  static List<Category> getCategories(String localeKey) {
    if (localeKey == 'ar') {
      return [
        // Main Categories
        Category(id: 'cat1',
            name: 'برجر',
            parentId: null,
            greenSvgPath: 'assets/images/burger.svg',
            whiteSvgPath: 'assets/images/burger1.svg'),
        Category(
          id: 'cat2',
          name: 'طعام',
          parentId: null,
          greenSvgPath: 'assets/images/food.svg',
          whiteSvgPath: 'assets/images/food1.svg',),
        Category(
          id: 'cat3',
          name: 'مشروبات',
          parentId: null,
          greenSvgPath: 'assets/images/drinks.svg',
          whiteSvgPath: 'assets/images/drinks1.svg',),
        Category(
          id: 'cat4',
          name: 'قهوة',
          parentId: null,
          greenSvgPath: 'assets/images/coffee.svg',
          whiteSvgPath: 'assets/images/coffee1.svg',
        ),
        Category(id: 'cat5',
            name: 'شوربات',
            parentId: null,
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(
          id: 'cat6',
          name: 'مقبلات',
          parentId: null,
          greenSvgPath: 'assets/images/appetizers.svg',
          whiteSvgPath: 'assets/images/appetizers1.svg',
        ),
        Category(
          id: 'cat7',
          name: 'حلويات',
          parentId: null,
          greenSvgPath: 'assets/images/desserts.svg',
          whiteSvgPath: 'assets/images/desserts1.svg',),
        Category(
          id: 'cat8',
          name: 'بيتزا',
          parentId: null,
          greenSvgPath: 'assets/images/pizza.svg',
          whiteSvgPath: 'assets/images/pizza1.svg',),
        // Sub Categories
        Category(id: 'sub1',
            name: 'مشروبات باردة',
            parentId: 'cat3',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub2',
            name: 'مشروبات ساخنة',
            parentId: 'cat3',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(
            id: 'sub3',
            name: 'برجر لحم',
            parentId: 'cat1',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub4',
            name: 'برجر دجاج',
            parentId: 'cat1',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub5',
            name: 'بيتزا بالخضار',
            parentId: 'cat8',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub6',
            name: 'بيتزا باللحوم',
            parentId: 'cat8',
            greenSvgPath: '',
            whiteSvgPath: ''),
      ];
    } else {
      return [
        // Main Categories
        Category(id: 'cat1',
            name: 'Burgers',
            parentId: null,
            greenSvgPath: 'assets/images/burger.svg',
            whiteSvgPath: 'assets/images/burger1.svg'),
        Category(
          id: 'cat2',
          name: 'Food',
          parentId: null,
          greenSvgPath: 'assets/images/food.svg',
          whiteSvgPath: 'assets/images/food1.svg',),
        Category(
          id: 'cat3',
          name: 'Drinks',
          parentId: null,
          greenSvgPath: 'assets/images/drinks.svg',
          whiteSvgPath: 'assets/images/drinks1.svg',),
        Category(
          id: 'cat4',
          name: 'Coffee',
          parentId: null,
          greenSvgPath: 'assets/images/coffee.svg',
          whiteSvgPath: 'assets/images/coffee1.svg',),
        Category(id: 'cat5',
            name: 'Soups',
            parentId: null,
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(
          id: 'cat6',
          name: 'Appetizers',
          parentId: null,
          greenSvgPath: 'assets/images/appetizers.svg',
          whiteSvgPath: 'assets/images/appetizers1.svg',
        ),
        Category(
          id: 'cat7',
          name: 'Desserts',
          parentId: null,
          greenSvgPath: 'assets/images/desserts.svg',
          whiteSvgPath: 'assets/images/desserts1.svg',),
        Category(
          id: 'cat8',
          name: 'Pizza',
          parentId: null,
          greenSvgPath: 'assets/images/pizza.svg',
          whiteSvgPath: 'assets/images/pizza1.svg',),
        // Sub Categories
        Category(id: 'sub1',
            name: 'Cold Drinks',
            parentId: 'cat3',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub2',
            name: 'Hot Drinks',
            parentId: 'cat3',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub3',
            name: 'Beef Burgers',
            parentId: 'cat1',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub4',
            name: 'Chicken Burgers',
            parentId: 'cat1',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub5',
            name: 'Vegetable Pizza',
            parentId: 'cat8',
            greenSvgPath: '',
            whiteSvgPath: ''),
        Category(id: 'sub6',
            name: 'Meat Pizza',
            parentId: 'cat8',
            greenSvgPath: '',
            whiteSvgPath: ''),
      ];
    }
  }

  static List<Ingredient> getIngredients(String localeKey) {
    if (localeKey == 'ar') {
      return [
        Ingredient(id: 'ing1', name: 'لحم بقري'),
        Ingredient(id: 'ing2', name: 'دجاج'),
        Ingredient(id: 'ing3', name: 'خبز'),
        Ingredient(id: 'ing4', name: 'جبنة'),
        Ingredient(id: 'ing5', name: 'خضار'),
        Ingredient(id: 'ing6', name: 'صلصة طماطم'),
        Ingredient(id: 'ing7', name: 'بطاطس'),
        Ingredient(id: 'ing8', name: 'شوكولاتة'),
        Ingredient(id: 'ing9', name: 'فانيليا'),
        Ingredient(id: 'ing10', name: 'قهوة'),
        Ingredient(id: 'ing11', name: 'حليب'),
        Ingredient(id: 'ing12', name: 'فطر'),
        Ingredient(id: 'ing13', name: 'زيتون'),
        Ingredient(id: 'ing14', name: 'كريمة'),
        Ingredient(id: 'ing15', name: 'سكر'),
      ];
    } else {
      return [
        Ingredient(id: 'ing1', name: 'Beef'),
        Ingredient(id: 'ing2', name: 'Chicken'),
        Ingredient(id: 'ing3', name: 'Bread'),
        Ingredient(id: 'ing4', name: 'Cheese'),
        Ingredient(id: 'ing5', name: 'Vegetables'),
        Ingredient(id: 'ing6', name: 'Tomato Sauce'),
        Ingredient(id: 'ing7', name: 'Potatoes'),
        Ingredient(id: 'ing8', name: 'Chocolate'),
        Ingredient(id: 'ing9', name: 'Vanilla'),
        Ingredient(id: 'ing10', name: 'Coffee'),
        Ingredient(id: 'ing11', name: 'Milk'),
        Ingredient(id: 'ing12', name: 'Mushrooms'),
        Ingredient(id: 'ing13', name: 'Olives'),
        Ingredient(id: 'ing14', name: 'Cream'),
        Ingredient(id: 'ing15', name: 'Sugar'),
      ];
    }
  }

  static List<Product> getProducts(String localeKey) {
    final categories = getCategories(localeKey);
    final ingredients = getIngredients(localeKey);

    return [
      Product(id: 'p1',
          name: localeKey == 'ar' ? 'برجر لحم كلاسيكي' : 'Classic Beef Burger',
          description: localeKey == 'ar' ? 'برجر لحم مع جبنة وخضار.' : 'Beef burger with cheese and veggies.',
          imagePath: '',
          price: '25000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub3'),
          releaseDate: DateTime(2025, 1, 10),
          ingredients: [ingredients[0], ingredients[2], ingredients[4]]),
      Product(id: 'p2',
          name: localeKey == 'ar' ? 'برجر دجاج مقرمش' : 'Crispy Chicken Burger',
          description: localeKey == 'ar' ? 'برجر دجاج مقرمش مع صلصة.' : 'Crispy chicken burger with sauce.',
          imagePath: '',
          price: '22000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub4'),
          releaseDate: DateTime(2025, 2, 15),
          ingredients: [ingredients[1], ingredients[2], ingredients[5]]),
      Product(id: 'p3',
          name: localeKey == 'ar' ? 'برجر دجاج بالجبنة' : 'Cheesy Chicken Burger',
          description: localeKey == 'ar' ? 'برجر دجاج مع جبنة لذيذة.' : 'Chicken burger with melted cheese.',
          imagePath: '',
          price: '24000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub4'),
          releaseDate: DateTime(2025, 3, 5),
          ingredients: [ingredients[1], ingredients[4], ingredients[3]]),
      Product(id: 'p4',
          name: localeKey == 'ar' ? 'بيتزا خضار' : 'Vegetable Pizza',
          description: localeKey == 'ar' ? 'بيتزا بالخضار الطازجة.' : 'Pizza with fresh vegetables.',
          imagePath: '',
          price: '45000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub5'),
          releaseDate: DateTime(2025, 3, 20),
          ingredients: [ingredients[4], ingredients[5], ingredients[3]]),
      Product(
          id: 'p5',
          name: localeKey == 'ar' ? 'بيتزا باللحم' : 'Meat Pizza',
          description: localeKey == 'ar' ? 'بيتزا باللحم والجبنة.' : 'Pizza with beef and cheese.',
          imagePath: '',
          price: '50000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub6'),
          releaseDate: DateTime(2025, 4, 2),
          ingredients: [ingredients[0], ingredients[5], ingredients[3]]),
      Product(id: 'p6',
          name: localeKey == 'ar' ? 'بطاطا مقلية' : 'French Fries',
          description: localeKey == 'ar' ? 'بطاطا مقرمشة.' : 'Crispy golden fries.',
          imagePath: '',
          price: '10000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat6'),
          releaseDate: DateTime(2025, 2, 10),
          ingredients: [ingredients[7]]),
      Product(id: 'p7',
          name: localeKey == 'ar' ? 'شوربة طماطم' : 'Tomato Soup',
          description: localeKey == 'ar' ? 'شوربة طماطم طازجة.' : 'Fresh tomato soup.',
          imagePath: '',
          price: '15000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat5'),
          releaseDate: DateTime(2025, 1, 15),
          ingredients: [ingredients[5], ingredients[14]]),
      Product(id: 'p8',
          name: localeKey == 'ar' ? 'شوربة فطر' : 'Mushroom Soup',
          description: localeKey == 'ar' ? 'شوربة فطر بالكريمة.' : 'Creamy mushroom soup.',
          imagePath: '',
          price: '17000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat5'),
          releaseDate: DateTime(2025, 2, 20),
          ingredients: [ingredients[12], ingredients[14]]),
      Product(id: 'p9',
          name: localeKey == 'ar' ? 'قهوة اسبريسو' : 'Espresso',
          description: localeKey == 'ar' ? 'قهوة اسبريسو مركزة.' : 'Strong espresso coffee.',
          imagePath: '',
          price: '12000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat4'),
          releaseDate: DateTime(2025, 3, 1),
          ingredients: [ingredients[10]]),
      Product(id: 'p10',
          name: localeKey == 'ar' ? 'قهوة بالحليب' : 'Café Latte',
          description: localeKey == 'ar' ? 'قهوة بالحليب الطازج.' : 'Coffee with milk.',
          imagePath: '',
          price: '14000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat4'),
          releaseDate: DateTime(2025, 3, 12),
          ingredients: [ingredients[10], ingredients[11]]),
      Product(id: 'p11',
          name: localeKey == 'ar' ? 'عصير برتقال' : 'Orange Juice',
          description: localeKey == 'ar' ? 'عصير برتقال طبيعي.' : 'Fresh orange juice.',
          imagePath: '',
          price: '13000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub1'),
          releaseDate: DateTime(2025, 1, 25),
          ingredients: [ingredients[5]]),
      Product(id: 'p12',
          name: localeKey == 'ar' ? 'عصير تفاح' : 'Apple Juice',
          description: localeKey == 'ar' ? 'عصير تفاح بارد.' : 'Chilled apple juice.',
          imagePath: '',
          price: '13000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub1'),
          releaseDate: DateTime(2025, 2, 8),
          ingredients: [ingredients[5]]),
      Product(id: 'p13',
          name: localeKey == 'ar' ? 'شاي ساخن' : 'Hot Tea',
          description: localeKey == 'ar' ? 'شاي أسود ساخن.' : 'Hot black tea.',
          imagePath: '',
          price: '9000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'sub2'),
          releaseDate: DateTime(2025, 1, 30),
          ingredients: [ingredients[14]]), // ✅ fixed
      Product(id: 'p14',
          name: localeKey == 'ar' ? 'كيك شوكولاتة' : 'Chocolate Cake',
          description: localeKey == 'ar' ? 'كيك بالشوكولاتة.' : 'Rich chocolate cake.',
          imagePath: '',
          price: '20000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat7'),
          releaseDate: DateTime(2025, 4, 5),
          ingredients: [ingredients[8], ingredients[14]]),
      Product(id: 'p15',
          name: localeKey == 'ar' ? 'كيك فانيليا' : 'Vanilla Cake',
          description: localeKey == 'ar' ? 'كيك بالفانيليا.' : 'Soft vanilla cake.',
          imagePath: '',
          price: '20000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat7'),
          releaseDate: DateTime(2025, 4, 8),
          ingredients: [ingredients[9], ingredients[14]]),
      Product(id: 'p16',
          name: localeKey == 'ar' ? 'آيس كريم شوكولاتة' : 'Chocolate Ice Cream',
          description: localeKey == 'ar' ? 'آيس كريم لذيذ بالشوكولاتة.' : 'Creamy chocolate ice cream.',
          imagePath: '',
          price: '12000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat7'),
          releaseDate: DateTime(2025, 5, 2),
          ingredients: [ingredients[8], ingredients[14]]),
      Product(id: 'p17',
          name: localeKey == 'ar' ? 'آيس كريم فانيليا' : 'Vanilla Ice Cream',
          description: localeKey == 'ar' ? 'آيس كريم بالفانيليا.' : 'Delicious vanilla ice cream.',
          imagePath: '',
          price: '12000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat7'),
          releaseDate: DateTime(2025, 5, 5),
          ingredients: [ingredients[9], ingredients[14]]),
      Product(id: 'p18',
          name: localeKey == 'ar' ? 'سلطة خضار' : 'Vegetable Salad',
          description: localeKey == 'ar' ? 'سلطة صحية بالخضار.' : 'Fresh vegetable salad.',
          imagePath: '',
          price: '18000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat2'),
          releaseDate: DateTime(2025, 2, 22),
          ingredients: [ingredients[5], ingredients[13]]),
      Product(id: 'p19',
          name: localeKey == 'ar' ? 'باستا بالخضار' : 'Vegetable Pasta',
          description: localeKey == 'ar' ? 'باستا بالخضار والصلصة.' : 'Pasta with vegetables and sauce.',
          imagePath: '',
          price: '30000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat2'),
          releaseDate: DateTime(2025, 3, 18),
          ingredients: [ingredients[5], ingredients[6], ingredients[13]]),
      Product(id: 'p20',
          name: localeKey == 'ar' ? 'سبرينغ رولز' : 'Spring Rolls',
          description: localeKey == 'ar' ? 'مقبلات مقرمشة بالخضار.' : 'Crispy vegetable rolls.',
          imagePath: '',
          price: '15000',
          isAvailable: true,
          category: categories.firstWhere((c) => c.id == 'cat6'),
          releaseDate: DateTime(2025, 2, 28),
          ingredients: [ingredients[5], ingredients[2]]),
    ];
  }
}
